### ISSUE TITLE
Question on library references when using QuotationCompiler

### ISSUE THREAD

**Issue by origfla** [eiriktsarpalis/QuotationCompiler#14]
I have a library (let's call it "Compiler") that uses QuotationCompiler to create an assembly. I am confused as to why my client application that uses the created assembly then needs a reference (at runtime) to the "Compiler" dll in order to run without error. The client does not also need a reference to QuotationCompiler.

The following is the error at runtime:

```

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Simple' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$Simple>.$Simple' threw an exception. ---> System.Runtime.Serialization.SerializationException: Unable to find assembly 'Marines.Compiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at <StartupCode$Simple>.$Simple..cctor()
   --- End of inner exception stack trace ---
   at Simple..cctor()
   --- End of inner exception stack trace ---
   at Simple.GetComputations()
   at Program.main(String[] argv) in C:\Users\sam\Documents\Code\Marines\BatchTester\Program.fs:line 52
Press any key to continue . . .

```

The only link is that "Compiler" created the assembly being used.

Is their a way to avoid this?

Aside: this could be linked to this question: https://github.com/fsharp/FSharp.Compiler.Service/issues/487
but note that it is NOT the same thing being asked.

**Comment by eiriktsarpalis** [comment]
By the stacktrace I understand that your compiled quotation encapsulates
dependencies to your compiler assembly. Avoid using any types or functions
defined in that assembly in order to remove the dependency.

**Comment by origfla** [comment]
Thanks. I checked and there is indeed code in the Compiler that will be used by the Compilee.
