### ISSUE TITLE
Why would the below not work in a dynamic assembly?

### ISSUE THREAD

**Issue by cognociente** [eiriktsarpalis/QuotationCompiler#7]
My use case is that I need to generate a whole set of semi-independent tree expressions and then would like to combine them and compile the whole thing in some sort of aggregate form. The following self-contained failure case is simulating the final step in my process which I can't seem to get working.

If this is a genuine limitation, what workaround would you suggest?

```
#r @"C:\Users\xxx\Source\Repos\QuotationCompiler\bin\QuotationCompiler.dll"

open System
open System.Reflection
open Microsoft.FSharp.Quotations

let input = [|1.0; 2.0; 3.0; 4.0; 5.0|]
let order = [|0;1;2;3;4|]
let stubs: (float[]->float)[] = [|for i in 0..order.Length-1 do yield (fun (r:float[]) -> 1.0)|] 

let result = System.Collections.Generic.Dictionary<int,float>()

let tree' = <@ order |> Array.iter (fun i -> result.[i] <- (stubs.[i] <| input)) @>
let ff1 = QuotationCompiler.QuotationCompiler.Eval tree'   // fails here

```

Error Message:

System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.get_Location()
   at <StartupCode$QuotationCompiler>.$QuotationCompiler.dependencies@117-1.Invoke(Assembly a) in C:\Users\\Source\Repos\QuotationCompiler\src\QuotationCompiler\QuotationCompiler.fs:line 117
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list)
>    at QuotationCompiler.QuotationCompiler.ToDynamicAssembly[a](a expr, FSharpOption`1 assemblyName) in C:\Users\\Source\Repos\QuotationCompiler\src\QuotationCompiler\QuotationCompiler.fs:line 117
   at <StartupCode$QuotationCompiler>.$QuotationCompiler.compile@130T.Invoke(a _arg1) in C:\Users\\Source\Repos\QuotationCompiler\src\QuotationCompiler\QuotationCompiler.fs:line 131
   at <StartupCode$QuotationCompiler>.$QuotationCompiler.ToFunc@140.Invoke(FSharpExpr arg) in C:\Users\\Source\Repos\QuotationCompiler\src\QuotationCompiler\QuotationCompiler.fs:line 140
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at QuotationCompiler.QuotationCompiler.ToFunc[T](FSharpExpr`1 expr, FSharpOption`1 useCache) in C:\Users\\Source\Repos\QuotationCompiler\src\QuotationCompiler\QuotationCompiler.fs:line 140
   at QuotationCompiler.QuotationCompiler.Eval[T](FSharpExpr`1 expr, FSharpOption`1 useCache) in C:\Users\\Source\Repos\QuotationCompiler\src\QuotationCompiler\QuotationCompiler.fs:line 150
   at <StartupCode$FSI_0005>.$FSI_0005.main@() in C:\temp\QuotationsCompilerTest\ConsoleApplication1\ConsoleApplication1\Indirect.fsx:line 46
Stopped due to error

Thanks
Sam

**Comment by eiriktsarpalis** [comment]
This happens because dynamic assemblies are in-memory entities that cannot be referenced by the F# compiler, which requires files. This can be avoided by keeping definitions captured by quotations in a class library and doing the compiled code normally through fsi.

**Comment by cognociente** [comment]
I understand: "This happens because dynamic assemblies are in-memory entities that cannot be referenced by the F# compiler, which requires files." but the rest I'm not so clear on...

Are you saying that `input, order, stubs & result` should all be defined in an external assembly for this to work?

**Comment by eiriktsarpalis** [comment]
Exactly.

**Comment by cognociente** [comment]
Thanks
